[build]
    command = "npm run build"
    publish= "dist"
[[redirects]]
    from = '/*'
    to = '/index.html'
[build.environment]:
    VITE_TINYMCE_API_KEY='nkh7rm8nod0r4p9279ryw9op497zfpo6o7hppclwy371j5df'